### ISSUE TITLE
Ввод капчи

### ISSUE THREAD

**Issue by UsualBread** [Whiletruedoend/Vk-to-telegram-transfer-bot#24]
Собственно, бот работает в контейнере. После того, как добавил новый чат, и перезагрузил его, стала прилетать капча... а куда вводить её - непонятно(

```
Enter Captcha https://api.vk.com/captcha.php?sid=191789883349: login in vk as: *****************

Successfully loginned in telegram!

Exception in thread Thread-1 (init_vk):

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.10/threading.py", line 953, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/src/app/./main.py", line 395, in init_vk

    vk_session.auth()

  File "/usr/local/lib/python3.10/site-packages/vk_api/vk_api.py", line 187, in auth

    self._auth_cookies(reauth=reauth)

  File "/usr/local/lib/python3.10/site-packages/vk_api/vk_api.py", line 207, in _auth_cookies

    self._vk_login()

  File "/usr/local/lib/python3.10/site-packages/vk_api/vk_api.py", line 312, in _vk_login

    return self.error_handlers[CAPTCHA_ERROR_CODE](captcha)

  File "/usr/src/app/./main.py", line 379, in captcha_handler

    key = input( "Enter Captcha {0}: ".format( captcha.get_url() ) ).strip()

EOFError: EOF when reading a line
```

**Comment by UsualBread** [comment]
`docker run -ti --entrypoint=sh %контейнер%`
`python /usr/src/app/main.py`
Проходим капчу, и всё работает. Оказалось, всё не так уж и сложно)
