### ISSUE TITLE
Ошибка при входе

### ISSUE THREAD

**Issue by DmytroSobol** [Whiletruedoend/Vk-to-telegram-transfer-bot#25]
Здравствуйте, в моменте когда надо ввести капчу ВК происходит ошибка. Пожалуйста помогите.

>Exception in thread Thread-1 (init_vk):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/./main.py", line 395, in init_vk
login in vk as: mail@gmail.com
Successfully loginned in telegram!
    vk_session.auth()
  File "/usr/local/lib/python3.11/site-packages/vk_api/vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "/usr/local/lib/python3.11/site-packages/vk_api/vk_api.py", line 207, in _auth_cookies
    self._vk_login()
  File "/usr/local/lib/python3.11/site-packages/vk_api/vk_api.py", line 330, in _vk_login
    self._pass_twofactor(response)
  File "/usr/local/lib/python3.11/site-packages/vk_api/vk_api.py", line 356, in _pass_twofactor
    code, remember_device = self.error_handlers[[TWOFACTOR_CODE]]()()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./main.py", line 371, in auth_handler
    key = input("Enter authentication code: ")
              ^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line

**Comment by nzargas** [comment]
У меня та же ошибка. Можно предположить, что это из-за двухфакторки, но у меня она не стоит, поэтому ошибка при введении капчи

**Comment by Whiletruedoend** [comment]
Вы через контейнер запускали?
Если да, то это потому что он не может считать вывод с контейнера. Нужно зайти в контейнер, запустить скрипт оттуда, закрыть скрипт и только после этого запустить контейнер. Тогда по идее должен запомнить. У меня нет аккаунта чтобы протестировать, но по идее должно работать.
